# Generated by Django 3.2 on 2022-05-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0003_auto_20220531_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.CharField(default='Product: ', max_length=300),
        ),
    ]
