# Generated by Django 3.2 on 2022-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0004_auto_20220531_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
