# Generated by Django 3.2 on 2022-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0006_remove_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
